# im:
#   - type: tg
#     token: xxxxx
#     masters: 
#       - 1000000

replies:
  #文本类型的回复
  - type: text
    rules:
      - 你好
    content: 我不好。
  #链接类型回复
  - type: url
    rules:
      - 壁纸
      - 二次元
    request:
        #图片
        response_type: image 
        url: https://acg.toubiec.cn/random.php

  - type: url
    rules:
      - 舔狗日记
    request:
        #纯文本
        response_type: text
        url: https://api.ixiaowai.cn/tgrj/index.php
  - type: url
    rules:
      - 股票 (.*)
    request:
        #纯文本
        response_type: text
        url: https://zyzcfa.com:444/api/stocks?keyword={{1}}
  - type: url
    rules:
      - 短网址 (.*)
    request:
        #纯文本
        response_type: json
        url: https://www.lzfh.com/api/dwz.php?cb=1&sturl=6&longurl={{1}}
        get: dwz_url
        
  # - type: url
  #   rules:
  #     - .*
  #   request:
  #       #纯文本
  #       response_type: json
  #       url: https://api.ixiaowai.cn/tgrj/index.php
  #       get: data.msg

